title: RiNOO
description: (A)synchronous socket management
avatar: https://github.com/reginaldl/librinoo/raw/master/doc/logo.png
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
